### ISSUE TITLE
TypeError: v is not a function

### ISSUE THREAD

**Issue by ResidentMario** [newsappsio/spam#27]
A recent change to the API seems to have broken [this chart](http://www.residentmar.io/2016/06/04/new-york-city-tree-density.html). Console reports: `TypeError: v is not a function`.

**Comment by lukasappelhans** [comment]
Thanks for the report. Can you put up a blocks with the code you are using to draw the map? (Or alternatively use the non-minified version for your blog post?)

**Comment by ResidentMario** [comment]
Yep&mdash;[here's the blocks version](http://bl.ocks.org/ResidentMario/36e786ac6b3fe62a13c4a42945bad1be).

**Comment by lukasappelhans** [comment]
Okay, the issue seems to be that http://cdn.rawgit.com/mourner/rbush/master/rbush.js results in a 404. When you use the non-minified version of spam.js, you will see that rbush is not defined. Can you confirm?

**Comment by ResidentMario** [comment]
Yep, doing this and reloading the page causes it to now raise `TypeError: rbush is not a function`.

**Comment by lukasappelhans** [comment]
Okay, let me close this issue then. :)

**Comment by ResidentMario** [comment]
I fixed the link and then backrolled rbush.js to `1.4.3`, neither of which caused it to start working again. Do you know what the fix is? It's casting a `TypeError: element.features is undefined` instead now.

**Comment by lukasappelhans** [comment]
It seems that after d3.json("merge_clean.json", function(error, data) {}) data is undefined. The error variable then says 'JSON.parse: end of data when property name was expected at line 34184 column 11 of the JSON data'.

**Comment by ResidentMario** [comment]
A JSON data source error? That's really odd; it had been working for the better part of a month until I spotted this a couple of days ago. I will look into it in a few; thanks for your help.
